Repository dotnet/arcade, pull requests merged in 2020-02, with the labels that each got.

#4766 Retries for GetDotNetInstallScript in powershell+bash
  eng/common/tools.ps1
  eng/common/tools.sh
Labels: First Responder

#4895 [Release/3.x] Set executable mode for SetupNugetSources.sh
  eng/common/SetupNugetSources.sh
Labels: servicing-consider

#4921 Support GenFacadesForceZeroVersionSeeds for source-based facades
  src/Microsoft.DotNet.GenFacades/ClearAssemblyReferenceVersions.cs
  src/Microsoft.DotNet.GenFacades/build/Microsoft.DotNet.GenPartialFacadeSource.targets
Labels: auto-merge
