Repository dotnet/arcade, pull requests merged in 2021-09, with the labels that each got.

#7829 Update version to 7.0
  eng/Versions.props
Labels: auto-merge

#7832 Added .Net 6 Eng and Validation channels
  src/Microsoft.DotNet.Build.Tasks.Feed/src/model/PublishingConstants.cs
Labels: auto-merge

#7883 Fix lld support
  eng/common/cross/toolchain.cmake
Labels: Engineering-ecosystem

#7884 Port to release/6.0: Fix lld support
  eng/common/cross/toolchain.cmake
Labels: Engineering-ecosystem

#7906 [release/6.0] x64 on arm64 fixes
  src/Common/wix/dotnethome_x64.wxs
  src/Microsoft.DotNet.Build.Tasks.Installers/Microsoft.DotNet.Build.Tasks.Installers.csproj
  src/Microsoft.DotNet.Build.Tasks.Installers/build/installer.singlerid.targets
  src/Microsoft.DotNet.Build.Tasks.Installers/build/wix/bundle/bundle.wxs
  src/Microsoft.DotNet.Build.Tasks.Installers/build/wix/product/product.wxs
  src/Microsoft.DotNet.Build.Tasks.Installers/build/wix/wix.targets
  src/Microsoft.DotNet.Build.Tasks.Installers/src/GenerateMacOSDistributionFile.cs
  src/Microsoft.DotNet.Build.Tasks.Workloads/src/EmbeddedTemplates.cs
  src/Microsoft.DotNet.Build.Tasks.Workloads/src/GenerateManifestMsi.cs
  src/Microsoft.DotNet.Build.Tasks.Workloads/src/GenerateMsiBase.cs
  src/Microsoft.DotNet.Build.Tasks.Workloads/src/Microsoft.DotNet.Build.Tasks.Workloads.csproj
  src/Microsoft.DotNet.Build.Tasks.Workloads/src/MsiTemplate/Directories.wxs
  src/Microsoft.DotNet.Build.Tasks.Workloads/src/MsiTemplate/ManifestProduct.wxs
Labels: servicing-approved

#7918 [6.0.1xx] Fix typo in mac installer generation script
  src/Microsoft.DotNet.Build.Tasks.Installers/src/GenerateMacOSDistributionFile.cs
Labels: servicing-approved

#7951 Additional RPMs for CBL-Mariner
  src/Microsoft.DotNet.Build.Tasks.SharedFramework.Sdk/targets/installer.targets
  src/Microsoft.DotNet.Build.Tasks.SharedFramework.Sdk/targets/packaging-tools.targets
Labels: servicing-consider

#7956 [release/6.0] Don't escape script content
  src/Microsoft.DotNet.Build.Tasks.Installers/src/GenerateMacOSDistributionFile.cs
Labels: servicing-approved
