Repository dotnet/arcade, pull requests merged in 2022-11, with the labels that each got.

#11465 Annotate some automated scan issues (rel/6.0)
  src/Microsoft.DotNet.Build.Tasks.Workloads/src/Swix/MsiSwixProject.wix.cs
  src/Microsoft.DotNet.Helix/Sdk/FindDotNetCliPackage.cs
Labels: First Responder, Operations

#11561 Add FAQ about stable packages
  Documentation/CorePackages/Publishing.md
Labels: auto-merge

#11689 Enable retries for `APP_CRASH` results on iOS/AppleTV devices
  src/Microsoft.DotNet.Helix/Sdk/tools/xharness-runner/xharness-event-processor.py
Labels: First Responder
